file_types_to_process:
  - epub
  - pdf
source_directory: C:\Users\Aaron\Documents\ebooks
target_directory: C:\Users\Aaron\Documents\target
create_opf_files: true
verbose: true
fetch_metadata_from:
  - goodreads
  - audible
  - mam
headless_mode: true